### ISSUE TITLE
Release files_external_s3 2.1.0

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/files_external_s3#1008]
### Reason
- Perfomance optimisations https://github.com/owncloud/files_external_s3/pull/1007

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Test plan -> https://github.com/owncloud/files_external_s3/issues/1012

### Documentation

- [ ] Changes in the docs needed? - > Release Notes

### Marketing

- [ ] Ping ownCloud Marketing
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries: https://github.com/owncloud/files_external_s3/releases/tag/v1.0.0RC1
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch @davitol https://github.com/owncloud/files_external_s3/issues/250

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Smoke test tarball (at least install + enable) @davitol 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by ChrisEdS** [comment]
@jnweiger FYI <3

**Comment by jnweiger** [comment]
Habemus RC1: https://github.com/owncloud/files_external_s3/releases/tag/v2.1.0-rc.1

**Comment by jnweiger** [comment]
## Issues seen while testin
- #1013 
- #1014

**Comment by jnweiger** [comment]
qa passed, release done.
