### ISSUE TITLE
aws server run automatically

### ISSUE THREAD

**Issue by TheBestNoobEver** [owncloud/files_external_s3#184]
Hello everybody, 

i have a server on aws.amazon and i wanted to know if it's possible to run it automatically like start it during from 9h45 to midnight for exemple without my computer ON to run my script.

Thanks if someone can help me !!

**Comment by DeepDiver1975** [comment]
This is Out of scope. Please redirect Your question to some aws forum or help Side.

**Comment by TheBestNoobEver** [comment]
ok, no prob
